version: "3.9"

services:
    nginx:
        image: nginx
        container_name: nginx
        hostname: nginx
        restart: always
        networks:
            - cms
        ports:
            - 80:80
        volumes:
            - ./nginx/maccms.conf:/etc/nginx/conf.d/default.conf
            - maccms:/www/maccms/

    mariadb:
        image: mariadb
        container_name: mariadb
        hostname: mariadb
        restart: always
        networks:
            - cms
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=123456

    
    maccms:
        image: dingzx97/cms:maccms
        container_name: maccms
        hostname: maccms
        restart: always
        networks:
            - cms
        volumes:
            - maccms:/var/www/html/

volumes:
    mariadb:
    maccms:

networks:
    cms:
